from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .iso_sprite_nodes import (
    NODE_CLASS_MAPPINGS as ISO_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as ISO_NAMES,
)
from .clip_info_nodes import (
    NODE_CLASS_MAPPINGS as CLIP_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as CLIP_NAMES,
)

NODE_CLASS_MAPPINGS.update(ISO_CLASSES)
NODE_CLASS_MAPPINGS.update(CLIP_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(ISO_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(CLIP_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
